<?php

namespace Database\Seeders;

use App\Models\CMS;
use App\Enums\PageEnum;
use App\Enums\SectionEnum;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CmsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear old data
        // CMS::truncate();

        /**
         * Hero section
         */

        // Landing Page - Hero Section
        $data = [
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::HERO->value,
                'name'            => 'item',
                'slug'            => null,
                'title'           => 'Simplify Fitness Testing for Students',
                'sub_title'       => null,
                'description'     => 'Ensure your students meet fitness standards with easy-to-use testing tools with 10 tests, automated scoring, instant reports & certificates',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            /**
             * Everything You Need for Student Fitness section
             */
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::EVERYTHING_YOU_NEED->value,
                'name'            => 'item',
                'slug'            => null,
                'title'           => 'Everything You Need for Student Fitness',
                'sub_title'       => null,
                'description'     => 'Comprehensive fitness assessment platform designed specifically for schools, fitness centers, and sports clubs.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            /**
             * Fitness Test Cards
             */
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::EVERYTHING_YOU_NEED->value,
                'name'    => 'card',
                'slug'    => '',
                'title'   => 'Easy Registration System',
                'sub_title'       => null,
                'description'     => 'Quick school registration with admin approval. Create accounts for entire year groups and manage student data efficiently.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::EVERYTHING_YOU_NEED->value,
                'name'    => 'card',
                'slug'    => '',
                'title'   => '10 Standardized Tests',
                'sub_title'       => null,
                'description'     => 'Comprehensive fitness assessment covering cardiovascular endurance, strength, flexibility, and coordination with age-gender based scoring.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::EVERYTHING_YOU_NEED->value,
                'name'            => 'card',
                'slug'            => null,
                'title'           => 'Instant Reports',
                'sub_title'       => null,
                'description'     => 'Generate detailed fitness reports with 5-level descriptors for each test. Track progress over time with visual charts and analytics.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::EVERYTHING_YOU_NEED->value,
                'name'            => 'card',
                'slug'            => null,
                'title'           => 'Digital Certificates',
                'sub_title'       => null,
                'description'     => 'Achievement badges and printable certificates recognize students attaining level 7 or above in fitness test modules.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::EVERYTHING_YOU_NEED->value,
                'name'            => 'card',
                'slug'            => null,
                'title'           => 'Downloadable Resources',
                'sub_title'       => null,
                'description'     => 'Access fitness specifications, recording sheets, and test guidelines. Everything you need for successful implementation.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::EVERYTHING_YOU_NEED->value,
                'name'            => 'card',
                'slug'            => null,
                'title'           => 'Secure Platform',
                'sub_title'       => null,
                'description'     => 'School-grade security ensures student data stays protected, while role-based admin controls keep access safe and accountable.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            /**
             * How it works
             */
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::HOW_IT_WORKS->value,
                'name'            => 'item',
                'slug'            => null,
                'title'           => 'How It Works',
                'sub_title'       => null,
                'description'     => 'Get started with FitnessQ in just a few simple steps',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            /**
             * How it words Cards
             */
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::HOW_IT_WORKS->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Register Your School',
                'sub_title'       => null,
                'description'     => 'Quickly register your school and get admin approval to create accounts for entire year groups.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::HOW_IT_WORKS->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Set Up Students',
                'sub_title'       => null,
                'description'     => 'Easily add students individually or in bulk. Manage student data efficiently with our user-friendly interface.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::HOW_IT_WORKS->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Conduct Fitness Tests',
                'sub_title'       => null,
                'description'     => 'Administer 10 standardized fitness tests using our easy-to-follow guidelines and recording sheets.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::HOW_IT_WORKS->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Get Instant Reports',
                'sub_title'       => null,
                'description'     => 'Generate comprehensive reports for individual students, classes, and entire schools in seconds. Track progress over time with historical data.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],


            /*
            * Comperehensive Fitness test
            */
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::READY_TO_TRANSFORM->value,
                'name'            => 'item',
                'slug'            => null,
                'title'           => 'Ready to Transform Student Fitness Testing?',
                'sub_title'       => null,
                'description'     => 'Join thousands of schools simplifying fitness assessments with FitnessQ.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => 'Get Started Now',
                'btn_link'        => '',
                'btn_color'       => '',
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],

            /*
            * Comperehensive Fitness test Cards
            */
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Agility',
                'sub_title'       => null,
                'description'     => 'Vertical jump, standing broad jump, and agility tests to assess lower body power and coordination.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Cardiovascular Endurance',
                'sub_title'       => null,
                'description'     => 'Multi-stage fitness test and endurance running assessments to evaluate aerobic capacity.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Flexibility',
                'sub_title'       => null,
                'description'     => 'Sit and reach tests to measure hamstring and lower back flexibility.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Muscular Strength & Endurance',
                'sub_title'       => null,
                'description'     => 'Push-up, sit-up, and handgrip strength tests to assess upper body and core strength.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Coordination',
                'sub_title'       => null,
                'description'     => 'Balance tests and hand-eye coordination challenges to evaluate motor skills.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Reaction',
                'sub_title'       => null,
                'description'     => 'Quick reflex drills, response speed, and coordination tests to assess reaction time.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Power',
                'sub_title'       => null,
                'description'     => 'Explosive strength tests, including sprints, jumps, and throws to measure power output.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Speed',
                'sub_title'       => null,
                'description'     => 'Sprint tests and reaction time measurements to evaluate quickness and acceleration.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Muscular Stamina',
                'sub_title'       => null,
                'description'     => 'Multi-stage fitness test and endurance running assessments to evaluate aerobic capacity.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
            [
                'page'    => PageEnum::HOW_IT_WORKS->value,
                'section' => SectionEnum::FITNESS_TEST->value,
                'name'    => 'card',
                'slug'    => null,
                'title'   => 'Muscular Stamina',
                'sub_title'       => null,
                'description'     => 'Muscular StaminaMulti-stage fitness test and endurance running assessments to evaluate aerobic capacity.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => null,
                'btn_link'        => null,
                'btn_color'       => null,
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],


            /*
             * Ready to transform section
            */
            [
                'page'            => PageEnum::HOW_IT_WORKS->value,
                'section'         => SectionEnum::READY_TO_TRANSFORM->value,
                'name'            => 'item',
                'slug'            => null,
                'title'           => 'Ready to Transform Student Fitness Testing?',
                'sub_title'       => null,
                'description'     => 'Join thousands of schools simplifying fitness assessments with FitnessQ.',
                'sub_description' => null,
                'bg'              => null,
                'image'           => '',
                'btn_text'        => 'Get Started Now',
                'btn_link'        => '/register',
                'btn_color'       => 'primary',
                'metadata'        => null,
                'created_at'      => now(),
                'updated_at'      => now(),
            ],
        ];

        foreach ($data as $row) {
            CMS::create($row);
        }
    }
}
