@extends('backend.app')

@section('title', 'Work Calendar')

@section('content')
    <div class="app-content main-content mt-0">
        <div class="side-app">
            <div class="main-container container-fluid" style="padding: 0;">

                {{-- page header --}}
                <div class="page-header">
                    <div class="card shadow-sm mb-2 border-0">
                        <div class="card-body d-flex justify-content-between align-items-center flex-wrap">
                            <div>
                                <h1 class="page-title mb-0">Calendar For Work Management</h1>
                            </div>
                        </div>
                    </div>
                </div>
                {{-- page header end --}}

                {{-- calendar integration --}}
                <div class="calendar-container">
                    <!-- Sidebar -->
                    <div class="calendar-sidebar">
                        <div class="sidebar-header">
                            <button class="create-btn" data-bs-toggle="modal" data-bs-target="#createWorkModal">
                                <i class="fas fa-plus"></i>
                                <span>Create</span>
                            </button>
                        </div>

                        <!-- Mini Calendar -->
                        <div class="mini-calendar">
                            <div class="mini-calendar-header">
                                <button class="mini-nav-btn" id="miniPrevMonth">
                                    <i class="fas fa-chevron-left"></i>
                                </button>
                                <span class="mini-calendar-title" id="miniCalendarTitle">October 2025</span>
                                <button class="mini-nav-btn" id="miniNextMonth">
                                    <i class="fas fa-chevron-right"></i>
                                </button>
                            </div>
                            <div class="mini-calendar-grid" id="miniCalendarGrid">
                                <!-- Calendar days will be generated by JavaScript -->
                            </div>
                        </div>

                        <!-- Filters -->
                        <div class="sidebar-filters">
                            <div class="filter-group">
                                <label class="filter-label">Team</label>
                                <select id="teamFilter" class="filter-select">
                                    <option value="">All Teams</option>
                                    @foreach ($teams as $team)
                                        <option value="{{ $team->id }}">{{ $team->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="filter-group">
                                <label class="filter-label">Status</label>
                                <select id="statusFilter" class="filter-select">
                                    <option value="">All Status</option>
                                    <option value="completed">Completed</option>
                                    <option value="pending">Pending</option>
                                    <option value="rescheduled">Rescheduled</option>
                                </select>
                            </div>

                            <div class="filter-group">
                                <label class="filter-label">Category</label>
                                <select id="categoryFilter" class="filter-select">
                                    <option value="">All Categories</option>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="google-sync-section">
                                <div class="sync-status">
                                    <i class="fab fa-google"></i>
                                    <span>Google Calendar</span>
                                    @if ($isGoogleConnected)
                                        <span class="status-badge connected">
                                            <i class="fas fa-check-circle"></i>
                                            Connected
                                        </span>
                                    @else
                                        <span class="status-badge disconnected">
                                            <i class="fas fa-times-circle"></i>
                                            Not Connected
                                        </span>
                                    @endif
                                </div>
                                <div class="sync-actions">
                                    @if ($isGoogleConnected)
                                        <button class="sync-btn primary" id="syncGoogleBtn"
                                            style="flex: 0 0 calc(80% - 4px);">
                                            <i class="fas fa-sync"></i> Sync
                                        </button>
                                        <a href="{{ route('google.disconnect') }}" class="sync-btn"
                                            style="flex: 0 0 calc(20% - 4px); display: flex; align-items: center; justify-content: center; text-decoration: none; color: #5f6368;">
                                            <i class="fas fa-unlink"></i>
                                        </a>
                                    @else
                                        <a href="{{ route('google.redirect') }}" class="sync-btn primary"
                                            style="flex: 1; text-align: center; text-decoration: none; color: white;">
                                            <i class="fab fa-google"></i> Connect
                                        </a>
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- Main Calendar -->
                    <div class="calendar-main">
                        <div class="calendar-header">
                            <div class="calendar-header-left">
                                <button class="today-btn" id="todayBtn">Today</button>
                                <div class="calendar-nav">
                                    <button class="nav-btn" id="prevBtn">
                                        <i class="fas fa-chevron-left"></i>
                                    </button>
                                    <button class="nav-btn" id="nextBtn">
                                        <i class="fas fa-chevron-right"></i>
                                    </button>
                                </div>
                                <h2 class="calendar-title" id="calendarTitle">October 2025</h2>
                            </div>
                            <div class="calendar-header-right">
                                <div class="view-switcher">
                                    <button class="view-btn active" data-view="dayGridDay">Day</button>
                                    <button class="view-btn" data-view="timeGridWeek">Week</button>
                                    <button class="view-btn" data-view="dayGridMonth">Month</button>
                                </div>
                            </div>
                        </div>
                        <div class="calendar-content">
                            <div id="calendar"></div>
                        </div>
                    </div>
                </div>
                {{-- calendar integration end --}}
            </div>
        </div>
    </div>

    <!-- CREATE/EDIT WORK MODAL -->
    @include('backend.layouts.calendar.add_edit')

    <!-- VIEW EVENT DETAILS MODAL -->
    @include('backend.layouts.calendar.view')
@endsection

@push('scripts')
    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.js'></script>

    <!-- Timepicker JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.js"></script>

    <!-- Google Maps API -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBfGOjmqKtEBRsfVN9szUo_tac20wcI9HM&libraries=places">
    </script>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const calendarEl = document.getElementById('calendar');
            let currentEventId = null;
            let selectedDates = [];
            let miniCalendarDate = new Date();
            let autocomplete;

            // Initialize Google Places Autocomplete
            function initAutocomplete() {
                const input = document.getElementById('location');

                // Clear any existing autocomplete
                if (autocomplete) {
                    google.maps.event.clearInstanceListeners(input);
                }

                // Create new autocomplete instance
                autocomplete = new google.maps.places.Autocomplete(input, {
                    types: ['geocode', 'establishment'],
                    fields: ['formatted_address', 'geometry', 'name']
                });

                // Listen for place selection
                autocomplete.addListener('place_changed', function() {
                    const place = autocomplete.getPlace();

                    if (!place.geometry) {
                        showToast('No details available for: ' + place.name, 'error');
                        return;
                    }

                    if (place.geometry) {
                        const lat = place.geometry.location.lat();
                        const lng = place.geometry.location.lng();

                        document.getElementById('latitude').value = lat;
                        document.getElementById('longitude').value = lng;
                        document.getElementById('location').value = place.formatted_address || place.name;

                        console.log('Location selected:', {
                            address: place.formatted_address || place.name,
                            lat: lat,
                            lng: lng
                        });
                    }
                });
            }

            // Wait for Google Maps to load before initializing
            function waitForGoogleMaps(callback) {
                if (typeof google !== 'undefined' && google.maps && google.maps.places) {
                    callback();
                } else {
                    setTimeout(() => waitForGoogleMaps(callback), 100);
                }
            }

            // Initialize autocomplete when ready
            waitForGoogleMaps(function() {
                initAutocomplete();
            });

            // Re-initialize autocomplete when modal opens
            $('#createWorkModal').on('shown.bs.modal', function() {
                setTimeout(function() {
                    waitForGoogleMaps(function() {
                        initAutocomplete();
                    });
                }, 300);
            });

            // Initialize FullCalendar
            const calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridDay',
                headerToolbar: false,
                editable: true,
                selectable: true,
                selectMirror: true,
                dayMaxEvents: true,
                weekends: true,
                height: '100%',
                displayEventTime: false,
                events: {
                    url: '{{ route('calendar.events') }}',
                    method: 'GET',
                    extraParams: function() {
                        return {
                            team_id: $('#teamFilter').val(),
                            status: $('#statusFilter').val(),
                            category_id: $('#categoryFilter').val()
                        };
                    },
                    failure: function() {
                        showToast('Failed to load events', 'error');
                    }
                },
                eventClick: function(info) {
                    info.jsEvent.preventDefault();
                    showEventDetails(info.event);
                },
                select: function(info) {
                    openCreateModal(info.startStr);
                },
                eventDrop: function(info) {
                    updateEventDate(info.event);
                },
                eventResize: function(info) {
                    updateEventDate(info.event);
                },
                datesSet: function(info) {
                    updateCalendarTitle(info.view);
                }
            });

            calendar.render();

            // Initialize Mini Calendar
            renderMiniCalendar();

            // Update calendar title
            function updateCalendarTitle(view) {
                const title = view.title;
                document.getElementById('calendarTitle').textContent = title;
            }

            // Render Mini Calendar
            function renderMiniCalendar() {
                const year = miniCalendarDate.getFullYear();
                const month = miniCalendarDate.getMonth();

                const monthNames = ['January', 'February', 'March', 'April', 'May', 'June',
                    'July', 'August', 'September', 'October', 'November', 'December'
                ];
                document.getElementById('miniCalendarTitle').textContent = `${monthNames[month]} ${year}`;

                const firstDay = new Date(year, month, 1).getDay();
                const daysInMonth = new Date(year, month + 1, 0).getDate();
                const daysInPrevMonth = new Date(year, month, 0).getDate();

                const grid = document.getElementById('miniCalendarGrid');
                grid.innerHTML = '';

                const dayHeaders = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
                dayHeaders.forEach(day => {
                    const header = document.createElement('div');
                    header.className = 'mini-calendar-day-header';
                    header.textContent = day;
                    grid.appendChild(header);
                });

                for (let i = firstDay - 1; i >= 0; i--) {
                    const day = daysInPrevMonth - i;
                    const dayEl = createMiniCalendarDay(day, year, month - 1, true);
                    grid.appendChild(dayEl);
                }

                const today = new Date();
                for (let day = 1; day <= daysInMonth; day++) {
                    const isToday = day === today.getDate() &&
                        month === today.getMonth() &&
                        year === today.getFullYear();
                    const dayEl = createMiniCalendarDay(day, year, month, false, isToday);
                    grid.appendChild(dayEl);
                }

                const totalCells = firstDay + daysInMonth;
                const remainingCells = 42 - totalCells;
                for (let day = 1; day <= remainingCells; day++) {
                    const dayEl = createMiniCalendarDay(day, year, month + 1, true);
                    grid.appendChild(dayEl);
                }
            }

            // Drag-to-select variables
            let isDragging = false;
            let dragStartDate = null;
            let dragEndDate = null;

            function createMiniCalendarDay(day, year, month, isOtherMonth, isToday = false) {
                const dayEl = document.createElement('div');
                dayEl.className = 'mini-calendar-day';
                if (isOtherMonth) dayEl.classList.add('other-month');
                if (isToday) dayEl.classList.add('today');
                dayEl.textContent = day;

                const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
                dayEl.dataset.date = dateStr;

                // Drag-to-select functionality
                dayEl.addEventListener('mousedown', function(e) {
                    e.preventDefault();
                    isDragging = true;
                    dragStartDate = dateStr;
                    dragEndDate = dateStr;
                    selectedDates = [dateStr];
                    updateSelectedDates();
                });

                dayEl.addEventListener('mouseenter', function() {
                    if (isDragging && dragStartDate) {
                        dragEndDate = dateStr;
                        selectedDates = getDateRange(dragStartDate, dragEndDate);
                        updateSelectedDates();
                    }
                });

                dayEl.addEventListener('mouseup', function() {
                    if (isDragging) {
                        isDragging = false;
                        dragEndDate = dateStr;
                        selectedDates = getDateRange(dragStartDate, dragEndDate);
                        updateSelectedDates();
                        filterCalendarByDates();
                    }
                });

                // Fallback: single click (for touch or non-drag)
                dayEl.addEventListener('click', function(e) {
                    if (!isDragging) {
                        document.querySelectorAll('.mini-calendar-day.selected').forEach(el => el.classList
                            .remove('selected'));
                        selectedDates = [dateStr];
                        updateSelectedDates();
                        filterCalendarByDates();
                    }
                });

                return dayEl;
            }

            // Helper: Update UI
            function updateSelectedDates() {
                document.querySelectorAll('.mini-calendar-day').forEach(el => {
                    el.classList.toggle('selected', selectedDates.includes(el.dataset.date));
                });
            }

            // Helper: Get all dates between two points
            function getDateRange(start, end) {
                const range = [];
                const startDate = new Date(start);
                const endDate = new Date(end);

                const step = startDate <= endDate ? 1 : -1;
                for (let d = new Date(startDate);
                    (step === 1 ? d <= endDate : d >= endDate); d.setDate(d.getDate() + step)) {
                    const formatted = d.toISOString().split('T')[0];
                    range.push(formatted);
                }
                return range;
            }

            // Global event listener to stop drag if mouse leaves calendar
            document.addEventListener('mouseup', () => {
                isDragging = false;
            });

            // Get date range between two dates
            function getDateRange(startStr, endStr) {
                const start = new Date(startStr);
                const end = new Date(endStr);
                const range = [];

                const [earlierDate, laterDate] = start <= end ? [start, end] : [end, start];
                const current = new Date(earlierDate);

                while (current <= laterDate) {
                    const dateStr = current.toISOString().split('T')[0];
                    range.push(dateStr);
                    current.setDate(current.getDate() + 1);
                }

                return range;
            }

            // Filter calendar by selected dates
            function filterCalendarByDates() {
                if (selectedDates.length === 0) {
                    return;
                }

                selectedDates.sort();
                const startDate = selectedDates[0];
                const endDate = selectedDates[selectedDates.length - 1];

                calendar.gotoDate(startDate);

                if (selectedDates.length === 1) {
                    calendar.changeView('dayGridDay', startDate);
                } else {
                    const daysDiff = Math.ceil((new Date(endDate) - new Date(startDate)) / (1000 * 60 * 60 * 24));
                    if (daysDiff <= 7) {
                        calendar.changeView('timeGridWeek', startDate);
                    } else {
                        calendar.changeView('dayGridMonth', startDate);
                    }
                }
            }

            // Mini calendar navigation
            document.getElementById('miniPrevMonth').addEventListener('click', function() {
                miniCalendarDate.setMonth(miniCalendarDate.getMonth() - 1);
                renderMiniCalendar();
            });

            document.getElementById('miniNextMonth').addEventListener('click', function() {
                miniCalendarDate.setMonth(miniCalendarDate.getMonth() + 1);
                renderMiniCalendar();
            });

            // Main calendar navigation
            document.getElementById('todayBtn').addEventListener('click', function() {
                calendar.today();
                miniCalendarDate = new Date();
                selectedDates = [new Date().toISOString().split('T')[0]];
                renderMiniCalendar();

                const todayStr = new Date().toISOString().split('T')[0];
                const todayEl = document.querySelector(`.mini-calendar-day[data-date="${todayStr}"]`);
                if (todayEl) {
                    todayEl.classList.add('selected');
                }
            });

            document.getElementById('prevBtn').addEventListener('click', function() {
                calendar.prev();
            });

            document.getElementById('nextBtn').addEventListener('click', function() {
                calendar.next();
            });

            // View switcher
            document.querySelectorAll('.view-btn').forEach(btn => {
                btn.addEventListener('click', function() {
                    document.querySelectorAll('.view-btn').forEach(b => b.classList.remove(
                        'active'));
                    this.classList.add('active');
                    calendar.changeView(this.dataset.view);
                });
            });

            // Filter change handlers
            $('#teamFilter, #statusFilter, #categoryFilter').on('change', function() {
                calendar.refetchEvents();
            });

            // Open create modal
            function openCreateModal(date = null) {
                $('#modalTitle').html('<i class="fas fa-calendar-plus me-2"></i>Create New Work Schedule');
                $('#workForm')[0].reset();
                $('#workId').val('');
                $('#formMethod').val('POST');
                $('#latitude').val('');
                $('#longitude').val('');

                if (date) {
                    $('#work_date').val(date);
                } else {
                    $('#work_date').val(new Date().toISOString().split('T')[0]);
                }

                $('#time').val('09:00');
                $('#createWorkModal').modal('show');
            }

            // Show event details in eventDetailsContent modal
            function showEventDetails(event) {
                currentEventId = event.id;
                const props = event.extendedProps;

                const startDate = new Date(event.start);
                const endDate = event.end ? new Date(event.end) : startDate;

                const statusBadge = props.completed ?
                    '<span class="badge bg-success">Completed</span>' :
                    (props.rescheduled ? '<span class="badge bg-warning">Rescheduled</span>' :
                        '<span class="badge bg-primary">Pending</span>');

                let dateTimeDisplay = '';
                if (props.is_all_day) {
                    dateTimeDisplay = `
                        <i class="far fa-calendar" style="margin-right: 8px;"></i>
                        ${startDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        ${endDate.getDate() !== startDate.getDate() ? ' - ' + endDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }) : ''}
                        <span class="badge bg-info ms-2">All Day</span>
                    `;
                } else {
                    dateTimeDisplay = `
                        <i class="far fa-calendar" style="margin-right: 8px;"></i>
                        ${startDate.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
                        <br>
                        <i class="far fa-clock" style="margin-right: 8px;"></i>
                        ${startDate.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })} -
                        ${endDate.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })}
                    `;
                }

                let detailsHtml = `
                    <div style="padding: 8px 0;">
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">TITLE</strong>
                            <div style="font-size: 16px; color: #3c4043; margin-top: 4px;">${event.title}</div>
                        </div>

                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">DATE & TIME</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">
                                ${dateTimeDisplay}
                            </div>
                        </div>

                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">STATUS</strong>
                            <div style="margin-top: 4px;">${statusBadge}</div>
                        </div>
                `;

                if (event.extendedProps.description) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">DESCRIPTION</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">${event.extendedProps.description}</div>
                        </div>
                    `;
                }

                if (event.extendedProps.location) {
                    const lat = props.latitude;
                    const lng = props.longitude;
                    const mapsUrl = lat && lng ?
                        `https://www.google.com/maps/search/?api=1&query=${lat},${lng}` :
                        `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(event.extendedProps.location)}`;

                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">LOCATION</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">
                                <i class="fas fa-map-marker-alt" style="margin-right: 8px;"></i>
                                <a href="${mapsUrl}" target="_blank" style="color: #1a73e8; text-decoration: none;">
                                    ${event.extendedProps.location}
                                    <i class="fas fa-external-link-alt" style="font-size: 12px; margin-left: 4px;"></i>
                                </a>
                            </div>
                        </div>
                    `;
                }

                if (props.team) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">TEAM</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">
                                <i class="fas fa-users" style="margin-right: 8px;"></i>
                                ${props.team}
                            </div>
                        </div>
                    `;
                }

                if (props.category) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">CATEGORY</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">
                                <i class="fas fa-tag" style="margin-right: 8px;"></i>
                                ${props.category}
                            </div>
                        </div>
                    `;
                }

                if (props.note) {
                    detailsHtml += `
                        <div style="margin-bottom: 16px;">
                            <strong style="color: #5f6368; font-size: 12px;">NOTE</strong>
                            <div style="font-size: 14px; color: #3c4043; margin-top: 4px;">${props.note}</div>
                        </div>
                    `;
                }

                detailsHtml += '</div>';

                $('#eventDetailsContent').html(detailsHtml);
                $('#viewEventModal').modal('show');
            }

            // Edit event
            $('#editEventBtn').on('click', function() {
                $('#viewEventModal').modal('hide');
                loadEventForEdit(currentEventId);
            });

            // Load event for editing
            function loadEventForEdit(eventId) {
                $.ajax({
                    url: `/calendar/${eventId}`,
                    method: 'GET',
                    success: function(work) {
                        console.log(work);

                        $('#modalTitle').html('<i class="fas fa-edit me-2"></i>Edit Work Schedule');
                        $('#workId').val(work.id);
                        $('#formMethod').val('PUT'); // Change to PUT for update
                        $('#title').val(work.title);
                        $('#description').val(work.description);
                        $('#location').val(work.location);
                        $('#latitude').val(work.latitude);
                        $('#longitude').val(work.longitude);
                        $('#team_id').val(work.team_id);
                        $('#category_id').val(work.category_id);
                        $('#note').val(work.note);

                        // Parse datetime fields
                        const startDateTime = new Date(work.start_datetime);
                        const endDateTime = new Date(work.end_datetime);

                        // Set work date from start_datetime
                        const workDate = startDateTime.toISOString().split('T')[0];
                        $('#work_date').val(workDate);

                        // Handle all day events
                        if (work.is_all_day) {
                            // Check the all day checkbox
                            $('#is_all_day').prop('checked', true);

                            // Hide time fields
                            $('#start_time_wrapper, #end_time_wrapper').hide();
                            $('#start_time, #end_time')
                                .prop('disabled', true)
                                .prop('required', false)
                                .val('');
                        } else {
                            // Uncheck all day checkbox
                            $('#is_all_day').prop('checked', false);

                            // Show time fields
                            $('#start_time_wrapper, #end_time_wrapper').show();
                            $('#start_time, #end_time')
                                .prop('disabled', false)
                                .prop('required', true);

                            // Format times to 12-hour format (h:i A)
                            const startTime = formatTime12Hour(startDateTime);
                            const endTime = formatTime12Hour(endDateTime);

                            $('#start_time').val(startTime);
                            $('#end_time').val(endTime);

                            // Reinitialize timepicker with values
                            $('#start_time, #end_time').timepicker('setTime', null);
                            $('#start_time').timepicker('setTime', startTime);
                            $('#end_time').timepicker('setTime', endTime);
                        }

                        $('#createWorkModal').modal('show');
                    },
                    error: function(xhr) {
                        console.error('Error loading work:', xhr);
                        showToast('Failed to load work details', 'error');
                    }
                });
            }

            // Handle form submission
            $('#saveWorkBtn').on('click', function(e) {
                e.preventDefault();

                let formData = new FormData($('#workForm')[0]);
                let id = $('#workId').val(); // Correct ID field
                let url = id ?
                    "{{ route('calendar.update', ':id') }}".replace(':id', id) :
                    "{{ route('calendar.store') }}";

                if (id) {
                    formData.append('_method', 'POST');
                }

                // Handle all day checkbox - ensure boolean is sent properly
                const isAllDay = $('#is_all_day').is(':checked');
                formData.set('is_all_day', isAllDay ? '1' : '0');

                // If all day, remove time fields
                if (isAllDay) {
                    formData.delete('start_time');
                    formData.delete('end_time');
                }

                $.ajax({
                    url: url,
                    type: 'POST',
                    data: formData,
                    contentType: false,
                    processData: false,
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    },
                    beforeSend: function() {
                        // Clear previous errors
                        $('.error-text').text('');
                        $('#saveWorkBtn').prop('disabled', true).html(
                            '<i class="fas fa-spinner fa-spin me-2"></i>Processing...');
                    },
                    success: function(response) {
                        if (response.status === false) {
                            // Validation errors
                            $.each(response.errors, function(field, messages) {
                                $('.' + field + '_error').text(messages[0]);
                            });
                            $('#saveWorkBtn').prop('disabled', false).html(
                                '<i class="fas fa-save me-2"></i>Save');
                        } else {
                            // Success
                            $('#createWorkModal').modal('hide');
                            $('#workForm')[0].reset();
                            calendar.refetchEvents(); // Refresh calendar
                            showToast(response.message || 'Work saved successfully!',
                                'success');
                            $('#saveWorkBtn').prop('disabled', false).html(
                                '<i class="fas fa-save me-2"></i>Save');
                        }
                    },
                    error: function(xhr) {
                        $('#saveWorkBtn').prop('disabled', false).html(
                            '<i class="fas fa-save me-2"></i>Save');

                        if (xhr.status === 422) {
                            // Validation errors
                            const errors = xhr.responseJSON.errors;
                            $.each(errors, function(field, messages) {
                                // Handle nested field names (e.g., start_time)
                                const fieldName = field.replace(/\./g, '_');
                                $('.' + fieldName + '_error').text(messages[0]);
                            });
                            showToast('Please fix the validation errors', 'error');
                        } else {
                            showToast(xhr.responseJSON?.message || 'Failed to save work',
                                'error');
                        }
                    }
                });
            });


            // Modal reset on close
            $('#createWorkModal').on('hidden.bs.modal', function() {
                $('#workForm')[0].reset();
                $('.error-text').text('');
                $('#workId').val('');
                $('#formMethod').val('POST');
                $('#start_time_wrapper, #end_time_wrapper').show();
                $('#start_time, #end_time').prop('disabled', false);
                $('#is_all_day').prop('checked', false);
            });


            // Open create modal - improved
            function openCreateModal(date = null) {
                $('#modalTitle').html('<i class="fas fa-calendar-plus me-2"></i>Create New Work Schedule');
                $('#workForm')[0].reset();
                $('#workId').val('');
                $('#formMethod').val('POST');
                $('#latitude').val('');
                $('#longitude').val('');
                $('.error-text').text('');

                // Set date
                if (date) {
                    $('#work_date').val(date);
                } else {
                    $('#work_date').val(new Date().toISOString().split('T')[0]);
                }

                // Set default times
                $('#start_time').val('09:00 AM');
                $('#end_time').val('05:00 PM');

                // Ensure time fields are visible
                $('#start_time_wrapper, #end_time_wrapper').show();
                $('#start_time, #end_time').prop('disabled', false);
                $('#is_all_day').prop('checked', false);

                $('#createWorkModal').modal('show');
            }

            // Delete button click
            $('#deleteEventBtn').on('click', function(e) {
                e.preventDefault();
                showDeleteConfirm(currentEventId);
            });

            // SweetAlert confirmation + delete request
            function showDeleteConfirm(id) {
                Swal.fire({
                    title: 'Are you sure you want to delete this work?',
                    text: 'If you delete this, it will be gone forever.',
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!',
                    cancelButtonText: 'Cancel'
                }).then((result) => {
                    if (result.isConfirmed) {
                        deleteItem(id);
                    }
                });
            }

            // AJAX delete function
            function deleteItem(id) {
                $.ajax({
                    url: `/calendar/${id}`,
                    method: 'DELETE',
                    data: {
                        _token: '{{ csrf_token() }}'
                    },
                    beforeSend: function() {
                        Swal.fire({
                            title: 'Deleting...',
                            text: 'Please wait while we remove the work.',
                            allowOutsideClick: false,
                            didOpen: () => Swal.showLoading()
                        });
                    },
                    success: function(response) {
                        Swal.close();
                        $('#viewEventModal').modal('hide');
                        calendar.refetchEvents();
                        showToast(response.message, 'success');
                    },
                    error: function() {
                        Swal.close();
                        showToast('Failed to delete work', 'error');
                    }
                });
            }


            // Update event date/time via drag
            function updateEventDate(event) {
                const startDate = new Date(event.start);

                const formData = {
                    _token: '{{ csrf_token() }}',
                    _method: 'POST',
                    title: event.title,
                    work_date: startDate.toISOString().split('T')[0],
                    time: startDate.toTimeString().split(' ')[0]
                };

                $.ajax({
                    url: `/calendar/${event.id}`,
                    method: 'POST',
                    data: formData,
                    success: function(response) {
                        showToast('Event updated successfully', 'success');
                    },
                    error: function() {
                        showToast('Failed to update event', 'error');
                        calendar.refetchEvents();
                    }
                });
            }

            // Sync from Google Calendar
            $('#syncGoogleBtn').on('click', function() {
                const btn = $(this);
                btn.prop('disabled', true).html('<i class="fas fa-spinner fa-spin"></i> Syncing...');

                $.ajax({
                    url: '{{ route('google.sync') }}',
                    method: 'POST',
                    data: {
                        _token: '{{ csrf_token() }}',
                        start: calendar.view.activeStart.toISOString(),
                        end: calendar.view.activeEnd.toISOString()
                    },
                    success: function(response) {
                        calendar.refetchEvents();
                        showToast(response.message, 'success');
                    },
                    error: function(xhr) {
                        const message = xhr.responseJSON?.message || 'Failed to sync';
                        showToast(message, 'error');
                    },
                    complete: function() {
                        btn.prop('disabled', false).html('<i class="fas fa-sync"></i> Sync');
                    }
                });
            });

            // Toast notification function
            function showToast(message, type = 'info') {
                const toast = $(`
                    <div class="toast-notification ${type}">
                        <i class="fas fa-${type === 'success' ? 'check-circle' : type === 'error' ? 'exclamation-circle' : 'info-circle'}" style="color: ${type === 'success' ? '#34a853' : type === 'error' ? '#ea4335' : '#4285f4'}"></i>
                        <span style="color: #3c4043; font-size: 14px;">${message}</span>
                    </div>
                `);

                $('body').append(toast);

                setTimeout(() => {
                    toast.fadeOut(300, function() {
                        $(this).remove();
                    });
                }, 3000);
            }

            // Session messages
            @if (session('success'))
                showToast('{{ session('success') }}', 'success');
            @endif

            @if (session('error'))
                showToast('{{ session('error') }}', 'error');
            @endif

            // Initialize with today selected
            const todayStr = new Date().toISOString().split('T')[0];
            selectedDates = [todayStr];
            setTimeout(() => {
                const todayEl = document.querySelector(`.mini-calendar-day[data-date="${todayStr}"]`);
                if (todayEl) {
                    todayEl.classList.add('selected');
                }
            }, 100);


            // Initialize 12-hour time picker
            $('.timepicker').timepicker({
                timeFormat: 'h:i A', // 12-hour format with AM/PM
                interval: 15, // 15 minute intervals
                dynamic: false,
                dropdown: true,
                scrollbar: true,
                startTime: '12:00 AM',
                endTime: '11:45 PM'
            });

            // All day checkbox toggle
            $('#is_all_day').on('change', function() {
                if ($(this).is(':checked')) {
                    $('#start_time, #end_time').prop('disabled', true).val('');
                    $('#start_time_wrapper, #end_time_wrapper').hide();
                } else {
                    $('#start_time, #end_time').prop('disabled', false);
                    $('#start_time_wrapper, #end_time_wrapper').show();
                }
            });
        });
    </script>


    {{-- Helper function to format time in 12-hour format --}}
    <script>
        function formatTime12Hour(date) {
            let hours = date.getHours();
            let minutes = date.getMinutes();
            let ampm = hours >= 12 ? 'PM' : 'AM';
            hours = hours % 12;
            hours = hours ? hours : 12; // 0 should be 12
            minutes = minutes < 10 ? '0' + minutes : minutes;
            return hours + ':' + minutes + ' ' + ampm;
        }
    </script>
@endpush

@push('scripts')
    <!-- FullCalendar -->
    <link href='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.css' rel='stylesheet' />

    <!-- Timepicker CSS -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.13.18/jquery.timepicker.min.css">

    {{-- calendar styiling --}}
    <style>
        :root {
            --google-blue: #13bfa6;
            --google-blue-hover: #13bfa6;
            --border-color: #dadce0;
            --sidebar-bg: #ffffff;
            --hover-bg: #f1f3f4;
            --selected-bg: #e8f0fe;
        }

        .calendar-container {
            display: flex;
            height: calc(100vh - 120px);
            background: #fff;
            border-radius: 8px;
            overflow: hidden;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);
            margin-bottom: 20px;
        }

        /* Sidebar Styles */
        .calendar-sidebar {
            width: 280px;
            border-right: 1px solid var(--border-color);
            display: flex;
            flex-direction: column;
            background: var(--sidebar-bg);
        }

        .sidebar-header {
            padding: 13px 20px;
            border-bottom: 1px solid var(--border-color);
        }

        .create-btn {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 12px 24px;
            background: var(--google-blue);
            color: white;
            border: none;
            border-radius: 24px;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s;
            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
            width: 100%;
            justify-content: center;
        }

        .create-btn:hover {
            background: var(--google-blue-hover);
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
        }

        .create-btn i {
            font-size: 18px;
        }

        /* Mini Calendar */
        .mini-calendar {
            padding: 8px 12px;
            flex-shrink: 0;
        }

        .mini-calendar-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 12px;
            padding: 0 8px;
        }

        .mini-calendar-title {
            font-size: 14px;
            font-weight: 500;
            color: #3c4043;
        }

        .mini-nav-btn {
            background: none;
            border: none;
            width: 32px;
            height: 32px;
            border-radius: 50%;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #5f6368;
            transition: background 0.2s;
        }

        .mini-nav-btn:hover {
            background: var(--hover-bg);
        }

        .mini-calendar-grid {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            gap: 2px;
        }

        .mini-calendar-day-header {
            text-align: center;
            font-size: 11px;
            font-weight: 500;
            color: #70757a;
            padding: 4px 0;
        }

        .mini-calendar-day {
            aspect-ratio: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 12px;
            border-radius: 50%;
            cursor: pointer;
            color: #3c4043;
            transition: all 0.2s;
        }

        .mini-calendar-day:hover {
            background: var(--hover-bg);
        }

        .mini-calendar-day.other-month {
            color: #9aa0a6;
        }

        .mini-calendar-day.today {
            background: var(--google-blue);
            color: white;
            font-weight: 600;
        }

        .mini-calendar-day.selected {
            background: var(--selected-bg);
            color: var(--google-blue);
            font-weight: 600;
        }

        .mini-calendar-day {
            user-select: none;
            cursor: pointer;
        }


        .mini-calendar-day.has-events::after {
            content: '';
            position: absolute;
            bottom: 2px;
            width: 4px;
            height: 4px;
            background: var(--google-blue);
            border-radius: 50%;
        }

        /* Filters Section */
        .sidebar-filters {
            padding: 16px 20px;
            border-top: 1px solid var(--border-color);
            overflow-y: auto;
            flex: 1;
        }

        .filter-group {
            margin-bottom: 20px;
        }

        .filter-label {
            font-size: 14px;
            font-weight: 500;
            color: #3c4043;
            margin-bottom: 8px;
            display: block;
        }

        .filter-select {
            width: 100%;
            padding: 8px 12px;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            font-size: 14px;
            color: #3c4043;
            background: white;
            cursor: pointer;
            transition: all 0.2s;
        }

        .filter-select:focus {
            outline: none;
            border-color: var(--google-blue);
            box-shadow: 0 0 0 2px rgba(26, 115, 232, 0.1);
        }

        .google-sync-section {
            padding: 12px;
            background: #f8f9fa;
            border-radius: 8px;
            margin-top: 16px;
        }

        .sync-status {
            display: flex;
            align-items: center;
            gap: 8px;
            font-size: 13px;
            color: #5f6368;
            margin-bottom: 12px;
        }

        .status-badge {
            display: inline-flex;
            align-items: center;
            gap: 4px;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 12px;
            font-weight: 500;
        }

        .status-badge.connected {
            background: #e6f4ea;
            color: #137333;
        }

        .status-badge.disconnected {
            background: #fce8e6;
            color: #c5221f;
        }

        .sync-actions {
            display: flex;
            gap: 8px;
        }

        .sync-btn {
            flex: 1;
            padding: 8px 12px;
            border-radius: 4px;
            font-size: 13px;
            font-weight: 500;
            border: 1px solid var(--border-color);
            background: white;
            cursor: pointer;
            transition: all 0.2s;
        }

        .sync-btn:hover {
            background: var(--hover-bg);
        }

        .sync-btn.primary {
            background: var(--google-blue);
            color: white;
            border: none;
        }

        .sync-btn.primary:hover {
            background: var(--google-blue-hover);
        }

        /* Main Calendar Area */
        .calendar-main {
            flex: 1;
            display: flex;
            flex-direction: column;
            overflow: hidden;
        }

        .calendar-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 16px 20px;
            border-bottom: 1px solid var(--border-color);
            background: white;
        }

        .calendar-header-left {
            display: flex;
            align-items: center;
            gap: 16px;
        }

        .today-btn {
            padding: 8px 16px;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            background: white;
            color: #3c4043;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s;
        }

        .today-btn:hover {
            background: var(--hover-bg);
        }

        .calendar-nav {
            display: flex;
            gap: 4px;
        }

        .nav-btn {
            width: 36px;
            height: 36px;
            border: none;
            background: none;
            border-radius: 50%;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #5f6368;
            transition: background 0.2s;
        }

        .nav-btn:hover {
            background: var(--hover-bg);
        }

        .calendar-title {
            font-size: 22px;
            font-weight: 400;
            color: #3c4043;
            margin-left: 16px;
        }

        .calendar-header-right {
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .view-switcher {
            display: flex;
            border: 1px solid var(--border-color);
            border-radius: 4px;
            overflow: hidden;
        }

        .view-btn {
            padding: 8px 16px;
            border: none;
            background: white;
            color: #5f6368;
            font-size: 14px;
            font-weight: 500;
            cursor: pointer;
            transition: all 0.2s;
            border-right: 1px solid var(--border-color);
        }

        .view-btn:last-child {
            border-right: none;
        }

        .view-btn:hover {
            background: var(--hover-bg);
        }

        .view-btn.active {
            background: var(--selected-bg);
            color: var(--google-blue);
        }

        .calendar-content {
            flex: 1;
            overflow: auto;
            background: #fff;
        }

        /* FullCalendar Custom Styles */
        .fc {
            font-family: 'Google Sans', 'Roboto', Arial, sans-serif;
        }

        .fc .fc-toolbar {
            display: none;
        }

        .fc-theme-standard td,
        .fc-theme-standard th {
            border-color: var(--border-color);
        }

        .fc-col-header-cell {
            padding: 12px 4px;
            font-size: 11px;
            font-weight: 500;
            color: #70757a;
            text-transform: uppercase;
            background: #fff;
        }

        .fc-daygrid-day-number {
            color: #3c4043;
            font-size: 12px;
            padding: 8px;
        }

        .fc-day-today {
            background-color: #e8f0fe !important;
        }

        .fc-day-today .fc-daygrid-day-number {
            background: var(--google-blue);
            color: white;
            width: 28px;
            height: 28px;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: 600;
        }

        .fc-event {
            border: none !important;
            border-radius: 4px;
            padding: 2px 6px;
            font-size: 12px;
            cursor: pointer;
            margin: 1px 2px;
            transition: all 0.2s;
        }

        .fc-event:hover {
            opacity: 0.85;
            transform: translateY(-1px);
        }

        .fc-event-title {
            font-weight: 500;
        }

        .fc-daygrid-event-dot {
            display: none;
        }

        /* Time Grid Styles */
        .fc-timegrid-slot {
            height: 48px;
        }

        .fc-timegrid-slot-label {
            font-size: 12px;
            color: #70757a;
        }

        /* Modal Styles */
        .modal-content {
            border: none;
            border-radius: 12px;
            box-shadow: 0 8px 24px rgba(0, 0, 0, 0.15);
        }

        .modal-header {
            background: white;
            border-bottom: 1px solid var(--border-color);
            padding: 20px 24px;
            border-radius: 12px 12px 0 0;
        }

        .modal-title {
            font-size: 18px;
            font-weight: 500;
            color: #3c4043;
        }

        .modal-body {
            padding: 24px;
        }

        .form-label {
            font-size: 14px;
            font-weight: 500;
            color: #3c4043;
            margin-bottom: 8px;
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .form-control,
        .form-select {
            border: 1px solid var(--border-color);
            border-radius: 4px;
            padding: 10px 12px;
            font-size: 14px;
            transition: all 0.2s;
        }

        .form-control:focus,
        .form-select:focus {
            border-color: var(--google-blue);
            box-shadow: 0 0 0 2px rgba(26, 115, 232, 0.1);
            outline: none;
        }

        .btn-primary {
            background: var(--google-blue);
            border: none;
            color: white;
            padding: 10px 24px;
            border-radius: 4px;
            font-size: 14px;
            font-weight: 500;
            transition: all 0.2s;
        }

        .btn-primary:hover {
            background: var(--google-blue-hover);
        }

        .btn-secondary {
            background: white;
            border: 1px solid var(--border-color);
            color: #5f6368;
            padding: 10px 24px;
            border-radius: 4px;
            font-size: 14px;
            font-weight: 500;
            transition: all 0.2s;
        }

        .btn-secondary:hover {
            background: var(--hover-bg);
        }

        /* Toast Notification */
        .toast-notification {
            position: fixed;
            top: 20px;
            right: 20px;
            background: white;
            padding: 16px 20px;
            border-radius: 8px;
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
            z-index: 9999;
            display: flex;
            align-items: center;
            gap: 12px;
            min-width: 300px;
            animation: slideIn 0.3s ease;
        }

        @keyframes slideIn {
            from {
                transform: translateX(400px);
                opacity: 0;
            }

            to {
                transform: translateX(0);
                opacity: 1;
            }
        }

        .toast-notification.success {
            border-left: 4px solid #34a853;
        }

        .toast-notification.error {
            border-left: 4px solid #ea4335;
        }

        .toast-notification.info {
            border-left: 4px solid #4285f4;
        }

        /* Responsive */
        @media (max-width: 768px) {
            .calendar-sidebar {
                position: fixed;
                left: -280px;
                z-index: 1000;
                height: 100vh;
                transition: left 0.3s;
            }

            .calendar-sidebar.open {
                left: 0;
            }
        }
    </style>

    <style>
        /* Google Places Autocomplete styling */
        .pac-container {
            z-index: 10000 !important;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
            margin-top: 2px;
        }

        .pac-item {
            padding: 10px;
            cursor: pointer;
            font-size: 14px;
        }

        .pac-item:hover {
            background-color: #f1f3f4;
        }

        .pac-icon {
            margin-right: 10px;
        }

        .pac-item-query {
            font-weight: 600;
            color: #202124;
        }
    </style>

    {{-- style for team and category selection --}}
    <style>
        .equal-box {
            min-height: 120px;
            background-color: #f8f9fa;
            /* light gray */
            border-radius: 8px;
            padding: 15px;
            display: flex;
            flex-direction: column;
            justify-content: center;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        }

        .equal-box label {
            font-weight: 600;
            margin-bottom: 8px;
            color: #333;
            display: flex;
            align-items: center;
            gap: 5px;
        }

        .equal-box select,
        .equal-box input {
            width: 100%;
            padding: 8px 10px;
            font-size: 14px;
            border: 1px solid #ced4da;
            border-radius: 6px;
            box-shadow: none;
            background-color: #fff;
        }

        /* Optional: cleaner hover/focus */
        .equal-box select:focus,
        .equal-box input:focus {
            border-color: #86b7fe;
            outline: none;
            box-shadow: 0 0 0 0.15rem rgba(13, 110, 253, 0.25);
        }

        .form-section {
            display: flex;
            gap: 20px;
        }

        .form-section .col-md-6 {
            flex: 1;
        }
    </style>
@endpush
